/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useScroll, useTransform } from "framer-motion"
import { motion } from 'framer-motion-3d'
import { degreesToRadians } from 'popmotion'

export const Laptop = ({isOpen, isHover, ...props}) => {
  const { nodes, materials } = useGLTF('/laptop.glb')

  const variants = {
    open: {rotateX:(0 * Math.PI) / 180,
            x: -0.03,
            y: 111.69,
            z: 2.84},
    closed: {rotateX:(105 * Math.PI) / 180,
              x: 0,
              y: 75,
              z: 39}
  }
  
  const laptopVariants = {
    rest: {
      transition: { duration: 0.7 }
    },
    hover: {
      rotateZ: 1,
      rotateY: 0.3,
      transition: {
        rotateZ: { duration: 1.5, ease: "linear", repeat: Infinity }
      }
    }
  };
  return (
    <group {...props} dispose={null}>
      <motion.group rotation={[-Math.PI / 2, 0, 0]} scale={0.03} 
        initial={false}
        animate={isHover ? "hover" : "rest"}
        variants={laptopVariants}
        // onHoverStart={() => {console.log(isHover);  setIsHover(true)}}
        // onHoverEnd={() => setIsHover(false)}
        // rotation={[Math.PI / 2, 0, degreesToRadians(360)]}
      >
        <motion.group 
          position={[-0.03, 111.69, 2.84]} 
          scale={3.37}
          initial={"closed"}
          animate={isOpen ? "open" : "closed"}
          transition={{
            delay: 0.5,
            duration: 1
          }}
          variants={variants}
        >
          <mesh geometry={nodes.Screen.geometry} material={materials.Namibia} position={[0.01, -33.13, -0.84]} scale={0.3} />
          <mesh geometry={nodes.Black_Inset.geometry} material={materials['Display Rim 1']} position={[0.01, -33.13, -0.84]} scale={0.3} />
          <mesh geometry={nodes.Rubber.geometry} material={materials['Display Rubber 1']} position={[0.01, -33.13, -0.84]} scale={0.3} />
          <mesh geometry={nodes.Screen_Back.geometry} material={materials['Body 2']} position={[0.01, -33.13, -0.84]} scale={0.3} />
        </motion.group>
        <mesh geometry={nodes.Keyboard.geometry} material={materials['Keyboard 2']} />
        <mesh geometry={nodes.Touch_Panel.geometry} material={materials['Touch Bar 1']} />
        <mesh geometry={nodes.Ports.geometry} material={materials['Ports 1']} />
        <mesh geometry={nodes.Touchpad.geometry} material={materials['Touchpad 1']} />
        <mesh geometry={nodes.Body.geometry} material={materials['Body 3']} />
      </motion.group>
    </group>
  )
}